version: '3.8'

services:
  audio-converter:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./converted:/app/converted
      - ./instance:/app/instance
    restart: unless-stopped 